try:
    print(a)
except NameError:
    print("Name error has occured")
except:
    print("Other error has occured")

